version: '3'

services:
    
  api:
    build: .
    ports: 
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin@database:5432/test_db  
    depends_on:
        - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db