"""add phonenumber field

Revision ID: 1dde6ba95a71
Revises: 0aabbc606564
Create Date: 2024-06-06 21:13:05.378638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dde6ba95a71'
down_revision = '0aabbc606564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('phonenumber')

    # ### end Alembic commands ###
