name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        env:
          AT_USERNAME: "sandbox"
          AT_API_KEY: ${{ secrets.AT_API_KEY }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB: ${{ secrets.PG_DB }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        run: |
          docker-compose -f "compose.yaml" build

      - name: Tag and push Docker image
        run: |
          docker tag customer-orders-service_api registry.heroku.com/customer-orders-service/web
          docker push registry.heroku.com/customer-orders-service/web

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app customer-orders-service
