# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Run the tests in various configurations
  pytest:
    runs-on: ubuntu-22.04

    strategy:
      # Keep running even if one variation of the job fails
      fail-fast: false
      matrix:
          python-version: ["3.10", "3.11", "3.12"]

    steps:
      # actions/setup-python@v5 has built-in functionality for caching and restoring dependencies. 
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run the tests
        run: |
          python -m pytest -v 
